//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class TableMain
    {
        public int id { get; set; }
        public string indexid { get; set; }
        public string year { get; set; }
        public string month { get; set; }
        public string day { get; set; }
        public string hour { get; set; }
        public string zsp { get; set; }
        public string planvalueproductionges { get; set; }
        public string planvalueproductionaes { get; set; }
        public string planvalueproductiontes { get; set; }
        public string sumtminges { get; set; }
        public string sumtminaes { get; set; }
        public string sumtmintes { get; set; }
        public string sumtgminges { get; set; }
        public string sumtgminaes { get; set; }
        public string sumtgmintes { get; set; }
        public string sumtmaxges { get; set; }
        public string sumtmaxaes { get; set; }
        public string sumtmaxtes { get; set; }
        public string planvaluedemand { get; set; }
        public string planvalueexport { get; set; }
        public string planvalueimport { get; set; }
        public string averpricebuy { get; set; }
        public string averpricecell { get; set; }
    }
}
